---

- name: install auditd package | package-08
  package:
    name: '{{ auditd_package }}'
    state: 'present'

- name: configure auditd | package-08
  template:
    src: 'etc/audit/auditd.conf.j2'
    dest: '/etc/audit/auditd.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: configure audit.rules
  template:
    src: 'etc/audit/audit.rules.j2'
    dest: '/etc/audit/audit.rules'
    owner: root
    group: root
    mode: 640
