---
- name: Install network manager for disabling wifi
  package:
    name: network-manager
    state: 'present'

- name: Disable wifi - oldversion nmcli
  shell: nmcli nm wifi off
  register: result
  ignore_errors: True

- name: Disable wifi - newversion nmcli
  shell: nmcli r wifi off
  when: "'Error' in result.stderr"
