---
- name: "pam_cracklib.so config"
  lineinfile:
    path: /etc/pam.d/common-password
    line: "password required pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1"
    state: present

- name: "Password lockout configuration"
  lineinfile:
    path: /etc/pam.d/login
    line: "auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900"
    state: present

- name: "Password reuse prevention"
  lineinfile:
    path: /etc/pam.d/common-password
    line: "password sufficient pam_unix.so remember=5"
    state: present
