---
- name: Uninstall special purpose packages
  package: 
    name: '{{ special_purpose_package }}'
    state: 'absent'

- name: Clean remove biosdevname
  shell: update-initramfs -u
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Uninstall http packages
  package: 
    name: '{{ special_http_packages }}'
    state: 'absent'
