---
- block:
   - name: install tcp wrapper
     package: 
        name: "tcpd" 
        state: "present"
     ignore_errors: yes
   - name: install tcp wrapper
     package:
        name: "tcp_wrappers"
        state: "present"
     ignore_errors: yes
   - name: set permission for hosts.allow
     file:   
        path: '/etc/hosts.allow'
        mode: 0644
   - name: set permission for hosts.deny
     file:
        path: '/etc/hosts.deny'
        mode: 0644
